---

- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes 


- name: remove obsolete dependencies
  become: true
  apt:
    autoremove: yes


- name: install dependencies
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

    
- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "Install rsync."
  become: true
  apt:
    name: rsync
    state: present