---

- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes


- name: remove expired deps
  become: yes
  apt:
    autoremove: yes


- name: install dependencies
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

    
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes